version: 2
updates:
  # Maintain Gradle dependencies in the root directory
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain NPM dependencies for JioSaavn proxy
  - package-ecosystem: "npm"
    directory: "/jiosaavn-piped-proxy"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]
